AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SecondLevelDomain:
    Description: "Second level domain name"
    Type: String
    Default: kusipay
  TopLevelDomain:
    Description: "Top level domain name"
    Type: String
    Default: com

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub "${SecondLevelDomain}.${TopLevelDomain}"
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ${SecondLevelDomain}.${TopLevelDomain}"

  Certficate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "*.${SecondLevelDomain}.${TopLevelDomain}"
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Sub "${SecondLevelDomain}.${TopLevelDomain}"
      DomainValidationOptions:
        - DomainName: !Sub "${SecondLevelDomain}.${TopLevelDomain}"
          HostedZoneId: !Ref HostedZone

Outputs:
  HostedZoneId:
    Description: "Hosted zone id"
    Value: !Ref HostedZone
    Export:
      Name: !Sub "${SecondLevelDomain}-${TopLevelDomain}-hostedzoneid"
  AcmCertificateArn:
    Description: "Acm certificate arn"
    Value: !Ref Certficate
    Export:
      Name: !Sub "${SecondLevelDomain}-${TopLevelDomain}-acmcertificatearn"
