AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Domain:
    Description: "Domain name"
    Type: String
    Default: kusipay.com

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref Domain
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ${Domain}"

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "*.${Domain}"
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Ref Domain
      DomainValidationOptions:
        - DomainName: !Ref Domain
          HostedZoneId: !Ref HostedZone

Outputs:
  HostedZoneId:
    Description: "Hosted zone id"
    Value: !Ref HostedZone
    Export:
      Name: "common-domain-hostedzoneid"
  AcmCertificateArn:
    Description: "Acm certificate arn"
    Value: !Ref Certficate
    Export:
      Name: !Sub "common-domain-acmcertificatearn"
  DomainName:
    Description: "Domain name"
    Value: !Ref Domain
    Export:
      Name: !Sub "common-domain-domain"
